name: Autograding
on: [push, workflow_dispatch]

jobs:
  autograde:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Autograde
        uses: education/autograding@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}